#!/usr/bin/env bash
# Original Author: Boris Guéry <guery.b@gmail.com>
# https://github.com/borisguery/git-keywords-checker
# Tweaked By: AJ Schmidt (replaced grep w/ ack, replaced sed w/ perl for use
# with regex lookaheads and lookbehinds)

# Add or remove keywords here
KEYWORDS_REGEX="var_dump\(|die\(|print_r\(|debug_print_var|console\.(debug|info|log|warn)\(|(?<![a-zA-Z])(ad|AD)(?![a-zA-Z])|(?<![a-zA-Z])(ads|ADS)(?![a-zA-Z])"
# Add extensions to check here
EXTENSIONS_REGEX="(.php$|.html$|.js$)"

ERRORS_BUFFER=""
TEXT_DEFAULT="\\033[0;39m"
TEXT_INFO="\\033[1;32m"
TEXT_ERROR="\\033[1;31m"
TEXT_UNDERLINE="\\0033[4m"
TEXT_BOLD="\\0033[1m"
VERBOSE=false

FILES=$(git diff --cached --name-only --diff-filter=ACMR)

echo -e "\\033[1;33m""Keywords Checker - Pre-Commit Hook" "$TEXT_DEFAULT"
echo

for FILE in $FILES; do 
     if [[ $FILE =~ $EXTENSIONS_REGEX ]]; then
        ERRORS=""
        while IFS=: read -ra RESULT; do
            if [ "$RESULT" != "" ]; then
                ERRORS="$ERRORS\n\tline $TEXT_BOLD${RESULT[1]}$TEXT_DEFAULT: "
                ERRORS="$ERRORS"$(sed -n ${RESULT[1]}p $FILE | perl -pe "s/($KEYWORDS_REGEX)/\\$TEXT_UNDERLINE\1\\$TEXT_DEFAULT/g")
                if [ "$ERRORS_BUFFER" != "" ]; then
                    ERRORS_BUFFER="$ERRORS_BUFFER\n$ERRORS"
                else
                    ERRORS_BUFFER="$ERRORS"
                fi
            fi
        done < <(ack -H --nogroup $KEYWORDS_REGEX $FILE)
        if [ "$ERRORS" != "" ]; then
            ERRORS="$TEXT_ERROR Errors found in $TEXT_BOLD$FILE$TEXT_DEFAULT$ERRORS"
            echo -e "$ERRORS"
        fi
     fi
done


if [ "$ERRORS_BUFFER" != "" ]; then
    echo 
    echo -e "$TEXT_ERROR" "There were errors or warnings, commit aborted." "$TEXT_DEFAULT"
    echo -e "$TEXT_INFO" "If you are sure you want to commit those files, use --no-verify option" "$TEXT_DEFAULT"

    exit 1
else
    echo -e "$TEXT_INFO" "All files are clean." "$TEXT_DEFAULT"
    exit 0
fi
